[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "அகரம்"
authors = [{name = "Naveen", email = "kmnaveen101@gmail.com"}]
dynamic = ["version", "description"]
